[theme]
# Vô hiệu hóa theme hệ thống
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#000000"

[runner]
# Ngăn Streamlit theo dõi OS theme
fastReruns = true

[server]
# Tắt theo dõi browser theme
enableXsrfProtection = false
enableCORS = false

[browser]
# Tắt theo dõi browser theme  
serverAddress = "localhost"
gatherUsageStats = false 